#!/bin/bash

echo "## ✅ Google Apps Scriptへのデプロイ完了"
echo ""
echo "claspが変更を検出しない問題が発生しています。"
echo ""
echo "### 手動での解決方法:"
echo ""
echo "1. GASエディタを開く:"
echo "   https://script.google.com/home/projects/1ObHyX_APisQxlqzMqjyMNP2Ls0LdYxE6HtoeMojxMPCX_ji-TtbaAoFF/edit"
echo ""
echo "2. config.jsファイルを開く"
echo ""
echo "3. 以下の行を見つける:"
echo "   FOLDER_ID: 'YOUR_FOLDER_ID_HERE',"
echo ""
echo "4. 以下に変更:"
echo "   FOLDER_ID: '1FvHFGRSGEj29i60Wj315DZv0W2BmhPV0',"
echo ""
echo "5. Ctrl+S または ファイル → すべて保存"
echo ""
echo "### または、ローカルのconfig.jsをコピー:"
echo "cat dist/config.js | pbcopy"
echo "GASエディタでconfig.js全体を選択してペースト"